spring:
  application:
    name: api-gateway
  cloud:
    sleuth:
      sampler:
        probability: 1.0
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cambio-service
          uri: lb://cambio-service
          predicates:
            - Path=/cambio-service/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book-service/**
        - id: openapi
          uri: lb://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
springdoc:
  swagger-ui:
    urls:
      - name: book-service
        url: /v3/api-docs/book-service
      - name: cambio-service
        url: /v3/api-docs/cambio-service
