server:
  port: 8888
spring:
  application:
    name: orben-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rhyanorben/orben-config-server.git
          username: rhyanorben
          password: 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
          default-label: main
          search-paths:
            - 'greeting-service*'
