name: Countinous integration with Github

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build Eureka Naming Server Container Image
        working-directory: ./firstProject/naming-server
        run: mvn spring-boot:build-image -DskipTests

      - name: Build API Gateway Container Image
        working-directory: ./firstProject/api-gateway
        run: mvn spring-boot:build-image -DskipTests

      - name: Build Cambio Microservice
        working-directory: ./firstProject/cambio-service
        run: mvn clean package -DskipTests

      - name: Build Book Microservice
        working-directory: ./firstProject/book-service
        run: mvn clean package -DskipTests

      - name: Build Docker Compose
        working-directory: ./firstProject
        run: docker compose build
